server:
  port: 8084

spring:
  application:
    name: notification-service
  profiles:
    active: local
  kafka:
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP:notification-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}

jwt:
  secret: ${JWT_SECRET:185ee9a8b7197f600752e1deb44cb3dfe89b14d1664f18ed85fc17d1a9c861ab}
