server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # =========================
        # OpenAPI docs por servicio
        # =========================
        - id: auth-service-openapi
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

        - id: inventory-service-openapi
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/v3/api-docs/inventory
          filters:
            - RewritePath=/v3/api-docs/inventory, /v3/api-docs

        - id: order-service-openapi
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v3/api-docs/order
          filters:
            - RewritePath=/v3/api-docs/order, /v3/api-docs

        - id: notification-service-openapi
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/v3/api-docs/notification
          filters:
            - RewritePath=/v3/api-docs/notification, /v3/api-docs

        - id: report-service-openapi
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/v3/api-docs/report
          filters:
            - RewritePath=/v3/api-docs/report, /v3/api-docs

        # =========================
        # Rutas funcionales
        # =========================
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**,/carts/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/reports/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth
      - name: inventory-service
        url: /v3/api-docs/inventory
      - name: order-service
        url: /v3/api-docs/order
      - name: notification-service
        url: /v3/api-docs/notification
      - name: report-service
        url: /v3/api-docs/report