eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true

services:
  inventory:
    base-url: ${SERVICES_INVENTORY_BASE_URL:http://INVENTORY-SERVICE}
  order:
    base-url: ${SERVICES_ORDER_BASE_URL:http://ORDER-SERVICE}
