spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 1234
  kafka:
    bootstrap-servers: 127.0.0.1:9092

notification:
  service:
    base-url: http://localhost:8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
