spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres-order:5432/order_db}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:1234}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

notification:
  service:
    base-url: ${NOTIFICATION_SERVICE_BASE_URL:http://notification-service:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: true
